[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pysettings"
version = "0.1.0"

[project.urls]
"Homepage" = "https://github.com/sryu1/pysettings"
"Bug Tracker" = "https://github.com/sryu1/pysettings/issues"
