[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pysettings"
description = "A python package for saving and loading using JSON files"
readme = "README.md"
requires-python = ">=3.7"
keywords = []
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "json"
    ]
dynamic = ["version"]

[project.optional-dependencies]
pdf = ["]
rest = []

[project.scripts]
my-script = ""
